### PR TITLE
Made various changes in various components of About page.

### PR DESCRIPTION
**Pull request by nidhi-bhanushali**
…ons/contactStyle.js

	modified:   src/assets/jss/material-kit-pro-react/views/aboutUsSections/teamStyle.js
	modified:   src/index.js
	modified:   src/views/AboutUsPage/AboutUsPage.js
	modified:   src/views/AboutUsPage/Sections/SectionContact.js
	modified:   src/views/AboutUsPage/Sections/SectionDescription.js
	modified:   src/views/AboutUsPage/Sections/SectionServices.js
	modified:   src/views/AboutUsPage/Sections/SectionTeam.js

### CODE REVIEW

**Review by DreamsOfImran — CHANGES_REQUESTED** [review]
image
Deployment is failing due to some warnings. Can you please fix those warnings?

**Comment by nidhi-bhanushali** [comment]
Yes , I'll do that

**Comment by nidhi-bhanushali** [comment]
I've removed those warnings.

**Comment by DreamsOfImran** [comment]
@nidhi-bhanushali Thank you for your wonderful contribution.

**Pull request merged**
