### PR TITLE
Added Contacts Page and embedded Chennai Map with Google Maps

### PR DESCRIPTION
**Pull request by Jaagrav**

### CODE REVIEW

**Comment by Jaagrav** [comment]
The map will only work on Localhost and the main website domain. The API key needs to secure right? That's why only specific domains are going to work for this.

**Comment by DreamsOfImran** [comment]
@Jaagrav Great work! Thank you for your contribution.

**Comment by Jaagrav** [comment]
You're welcome @DreamsOfImran , I was going through your to-dos... If you could make the Email sending functionality from contact page an issue, then I'd be more than happy to help!

**Comment by DreamsOfImran** [comment]
@Jaagrav Sure. I'll create an issue for it.

**Pull request merged**
